### ISSUE TITLE
Collect data on alcohol

### ISSUE THREAD

**Issue by codystanfield** [crakkerjak/cs373-idb#6]

**Comment by codystanfield** [comment]
Need to find source of data that exposes a RESTful interface, and write a script to consume it.

**Comment by brettcox** [comment]
http://www.thecocktaildb.com/

**Comment by codystanfield** [comment]
Writing scraper to get the data

**Comment by codystanfield** [comment]
The data in [http://www.thecocktaildb.com/](http://www.thecocktaildb.com/) is incredibly inconsistent, need to manually look through ingredients returned to see what needs to be filtered out.

For example, measurements are sometimes in shots, ounces, jiggers, etc. Sometimes the measurement consists solely of '\n', or even just ' '. Most measurements seem to have a space at the end of the string.

**Comment by codystanfield** [comment]
Work done in acea3d1a41cacbd87e4feec34a27e6cebb08d12c and d25ced045622b25cdabec76444a063c3b1db57d3
