### ISSUE TITLE
Implement the API from the group below us

### ISSUE THREAD

**Issue by brettcox** [crakkerjak/cs373-idb#72]

**Comment by seshutter** [comment]
We have group 8, from 10am:

Group name: SudsDB
Project name: Tipsy Turkey

Members:
Trevor Adam (10 am)
Kenneth Hollinger (10 am)
Vineeth Krishnan (10 am)
Eric Symmank (10 am)
Peter Hong (1 pm)

Example models:
Brewery (Name, location)
Beers (ID, name, ABV, type)

Proposed project: 
A database of breweries around the country and the beers they offer.

Data sources:
http://www.brewerydb.com/developers
