### ISSUE TITLE
Create a critique of another group's website by answering the questions in the comment below

### ISSUE THREAD

**Issue by seshutter** [crakkerjak/cs373-idb#75]
What did they do well?
What did we learn from their website?
What can they do better?
What puzzles us about their website?

Have same group as the one we have to exercise the API from

**Comment by ctimaeus** [comment]
A draft:

## Critique of SudsDB

## What did they do well?

Nice template choice and excellent initial impression! Did you make that loading GIF? Either way, it's awesome. Images look great. Data layout is generally clean and clear. Style is consistent across the site. The little icons on pages for individual beers are a nice touch.

## What did we learn from their website?

Goose Island Beer Company makes a number of beers that are seriously high in alcohol content. The ability to sort a large number of beers by alcohol content seems inherently dangerous, though we tested it and survived. Despite extensive experience with the subject matter, we had to look up what IBU (international bitterness units) meant.

## What can they do better?

Column width and collapsed content is unintuitive. When the page is viewed in lower width windows column linking becomes non-functional. Only the last column is linked, and it is hidden in smaller viewports such as mobile devices. The right pagination arrow suffers the same fate.

## What puzzles us about their website?

Where did that GIF come from?
